# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.delete_all
School.delete_all
Style.delete_all
Membership.delete_all
Follower.delete_all
UserSchoolStyle.delete_all
Logo.delete_all
Photo.delete_all

User.create(first_name: 'Joe', email: 'joe.biggica@gmail.com', style: 'Hung Ga Kung Fu', password: 'joe', profile_url: "http://fc09.deviantart.net/fs71/f/2011/148/5/d/5d62446baab75b8a9898af496c480103-d3hfie9.jpg")
User.create(first_name: 'Tim', email: 'tim@gmail.com', style: 'MMA', password: 'tim', profile_url: "http://fc09.deviantart.net/fs71/f/2011/148/5/d/5d62446baab75b8a9898af496c480103-d3hfie9.jpg")
User.create(first_name: 'Conor', email: 'conor@gmail.com', style: 'MMA', password: 'conor', profile_url: "http://fc09.deviantart.net/fs71/f/2011/148/5/d/5d62446baab75b8a9898af496c480103-d3hfie9.jpg")
User.create(first_name: 'Adrian', email: 'adrian@gmail.com', style: 'Krav Maga', password: 'adrian', profile_url: "http://fc09.deviantart.net/fs71/f/2011/148/5/d/5d62446baab75b8a9898af496c480103-d3hfie9.jpg")
User.create(first_name: 'Jeff', email: 'jeff@gmail.com', style: 'Karate', password: 'jeff', profile_url: "http://fc09.deviantart.net/fs71/f/2011/148/5/d/5d62446baab75b8a9898af496c480103-d3hfie9.jpg")

School.create(logo_url: "./fist_avatar.png", name: "Fong's Hung Ga Kung Fu", address: "95 Lincoln Ave", city: "Staten Island", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "Tiger Schulmann's Mixed Martial Arts", address: "2nd Ave", city: "New York", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "Dragon Kim's Karate", address: "933 Richmond Ave", city: "Staten Island", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "Krav Maga Federation", address: "124 W 25th St", city: "New York", state: "NY")
School.create(logo_url: "./fist_avatar.png", name: "NY Martial Arts Academy", address: "253-26 Northern Blvd", city: "New York", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "Anderson's Martial Arts Academy", address: "394 Broadway", city: "New York", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "Urban Martial Arts", address: "965 Coney Island Ave", city: "New York", state: "NY")
School.create(logo_url: "./fist_avatar.png", name: "Bronx Martial Arts Academy", address: "1051 Allerton Ave", city: "New York", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "NYC Shotokan Karate Dojo", address: "55 Lexington Ave", city: "New York", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "Wing Chun Kung Fu", address: "132-18 33rd Ave", city: "New York", state: "NY")
School.create(logo_url: "./fist_avatar.png", name: "Yip Pui Wing Chun Martial Arts", address: "440 Lafayette St", city: "New York", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "Choy Lee Fut Kung Fu Sydney", address: "15 Goulburn St", city: "Haymarket", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")
School.create(logo_url: "./fist_avatar.png", name: "New York Hung Ga", address: "151 W 26th St", city: "New York", state: "NY", email: 'something@gmail.com', phone_number: "(123)-456-7890", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor eleifend sodales. Nunc aliquet commodo consectetur. Vestibulum diam nulla, fermentum eget cursus sit amet, viverra vel augue. Mauris hendrerit mauris et mi fringilla, cursus dignissim mauris consequat. Nullam ut arcu elementum justo volutpat auctor ac ut ante. Mauris nec imperdiet mauris. Nullam non augue venenatis, sollicitudin elit id, mollis ex. Morbi ut viverra nisl, eget hendrerit mi. Pellentesque dignissim sodales quam, at varius massa maximus et. Integer eget elementum massa, sit amet vestibulum dolor. Etiam dictum vel risus eget facilisis. Etiam quis laoreet elit. Proin finibus ex sapien, et fermentum diam ultricies id.  Nulla semper convallis dolor a efficitur. Suspendisse quis augue auctor, commodo justo sed, efficitur nunc. Morbi ac suscipit tellus, nec efficitur mi. Ut semper vitae nulla quis tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a turpis at odio congue tincidunt venenatis eu mi. Etiam quis urna eu leo tempor gravida. Proin in justo in dui pharetra pharetra non nec mi. Etiam malesuada dictum facilisis. Morbi sollicitudin lectus sed lorem laoreet tempor. Phasellus accumsan erat at neque mollis, vitae bibendum enim tincidunt. Nam suscipit lectus nec turpis commodo interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed semper lacus ac augue porta congue. Fusce at leo massa. Praesent justo justo, pulvinar quis auctor id, vestibulum ut neque. Ut ut turpis ut neque iaculis malesuada quis ut metus. Suspendisse cursus vulputate sodales. Suspendisse rutrum diam ac ultricies aliquam. Quisque in justo elementum risus suscipit finibus eget id tortor. Vivamus elit nisi, porta eu scelerisque eget, ultricies a mauris. Vestibulum odio odio, facilisis nec hendrerit eget, efficitur eget tellus. Vivamus porttitor felis at sem consectetur pulvinar. Vestibulum sit amet magna vestibulum, dapibus nibh vel, pulvinar tellus. Ut scelerisque eget magna eget maximus. Maecenas vitae leo vel nibh dapibus tempus. Ut id leo eget enim dignissim auctor.")

Style.create(name: 'Hung Ga Kung Fu')
Style.create(name: 'Krav Maga')
Style.create(name: 'Karate')
Style.create(name: 'MMA')
Style.create(name: 'Tae Kwon Do')
Style.create(name: 'Choy Lee Fut Kung Fu')
Style.create(name: 'Wing Chun Kung Fu')
Style.create(name: 'Shotokan Karate')

UserSchoolStyle.create(school_id: 1, style_id: 1)
UserSchoolStyle.create(school_id: 2, style_id: 4)
UserSchoolStyle.create(school_id: 3, style_id: 5)
UserSchoolStyle.create(school_id: 4, style_id: 2)
UserSchoolStyle.create(school_id: 5, style_id: 4)
UserSchoolStyle.create(school_id: 6, style_id: 4)
UserSchoolStyle.create(school_id: 7, style_id: 4)
UserSchoolStyle.create(school_id: 8, style_id: 4)
UserSchoolStyle.create(school_id: 9, style_id: 8)
UserSchoolStyle.create(school_id: 10, style_id: 7)
UserSchoolStyle.create(school_id: 11, style_id: 7)
UserSchoolStyle.create(school_id: 12, style_id: 6)
UserSchoolStyle.create(school_id: 13, style_id: 1)

UserSchoolStyle.create(user_id: 1, style_id: 1)
UserSchoolStyle.create(user_id: 2, style_id: 2)
UserSchoolStyle.create(user_id: 3, style_id: 2)
UserSchoolStyle.create(user_id: 4, style_id: 4)
UserSchoolStyle.create(user_id: 5, style_id: 3)

Membership.create(user_id: 1, school_id: 1)
Membership.create(user_id: 2, school_id: 2)
Membership.create(user_id: 3, school_id: 2)
Membership.create(user_id: 4, school_id: 4)
Membership.create(user_id: 5, school_id: 3)

Follower.create(user_id: 1, school_id: 1)
Follower.create(user_id: 2, school_id: 2)
Follower.create(user_id: 1, school_id: 3)
Follower.create(user_id: 3, school_id: 1)
Follower.create(user_id: 1, school_id: 1)











